### ISSUE TITLE
Splash screen / short guide

### ISSUE THREAD

**Issue by MagnusThor** [MagnusThor/kollokvium#1]
We need to add a spash-screen , an overlay , boostrap modal that show instructions, a short guide how it works...

When user close, we just set a property on the UserSettings class that prevents it to be shown again, as well as we can add a icon (help) that enables users to lauch it again.  I'm assiging this to @kaista82

**Comment by kaista82** [comment]
Should now be visible (Question mark top left)
https://github.com/MagnusThor/kollokvium/commit/34c5bad84e1987d0184d0f72e8a277c34e4e08d4
